services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sacilotto.andre@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_network
    deploy:
      # Traefik needs o run on manager for Docker socket access
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
      labels:
        - "traefik.enable=true"

  postgres_primary:
    image: norohim/postgres-optimal:latest
    environment:
      - ROLE=primary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - NODE_ID=1
      - NODE_NAME=primary
      - NODE_HOST=postgres_primary
    volumes:
      - primary_data:/var/lib/postgresql/data
    networks:
      - backend_network
    deploy:
      replicas: 1
      # Primary DB should be on manager for reliability
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=false"
    ports:
      - "5432:5432"

  postgres_replica:
    image: norohim/postgres-optimal:latest
    environment:
      - ROLE=replica
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - NODE_ID=2
      - NODE_NAME=replica1
      - NODE_HOST=postgres_replica
      - REPLICATE_FROM=postgres_primary
    volumes:
      - replica_data:/var/lib/postgresql/data
    networks:
      - backend_network
    depends_on:
      - postgres_primary
    deploy:
      replicas: 1
      # Place replica on worker to distribute DB load and for failover readiness
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=false"
    ports:
      - "5433:5432"

  pgbouncer:
    image: norohim/pgbouncer:latest
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - backend_network
    deploy:
      replicas: 2
      # Use global to place one instance on each node
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=false"
    ports:
      - "6432:6432"

  backend:
    image: norohim/cp-planta-backend:latest
    environment:
      - NODE_ENV=production
      - DB_HOST=pgbouncer
      - DB_PORT=6432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DATABASE_URL=postgresql://postgres:postgres@pgbouncer:6432/postgres
    networks:
      - backend_network
      - traefik_network
    deploy:
      replicas: 2
      # Distribute backend across both manager and worker
      placement:
        preferences:
          - spread: node.role
      resources:
        limits:
          cpus: '0.40'
          memory: 384M
        reservations:
          cpus: '0.20'
          memory: 192M
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.cpplanta.duckdns.org`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=myresolver"
        - "traefik.http.services.backend.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
        
  pgadmin:
    image: norohim/pgadmin:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=sacilotto.andre@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SecurePassword123
    depends_on:
      - postgres_primary
    networks:
      - backend_network
      - traefik_network
    deploy:
      replicas: 1
      # Preferably on worker to distribute admin tools
      placement:
        preferences:
          - spread: node.role
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 96M
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.cpplanta.duckdns.org`)"
        - "traefik.http.routers.pgadmin.entrypoints=websecure"
        - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin 

  frontend:
    image: norohim/cp-planta-frontend:latest
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_URL=https://api.cpplanta.duckdns.org
    networks:
      - frontend_network
      - traefik_network
    deploy:
      replicas: 2
      # Distribute frontend across both nodes
      placement:
        preferences:
          - spread: node.role
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`cpplanta.duckdns.org`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=myresolver"
        - "traefik.http.services.frontend.loadbalancer.server.port=3001"

  dns:
    image: coredns/coredns:1.9.3
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile
      - ./dns/zones:/etc/coredns/zones
    networks:
      - backend_network
      - frontend_network
      - traefik_network
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=false"
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  duckdns:
    image: linuxserver/duckdns:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo  
      - SUBDOMAINS=cpplanta
      - TOKEN=ab25d043-0943-4338-88c7-315b3973ca90  
      - LOG_FILE=false
    networks:
      - traefik_network
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M
      restart_policy:  
        condition: any
      labels:
        - "traefik.enable=false"

  visualizer:
    image: dockersamples/visualizer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_network
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true".e
        - "traefik.http.routers.visualizer.rule=Host(`viz.cpplanta.duckdns.org`)"
        - "traefik.http.routers.visualizerntrypoints=websecure"
        - "traefik.http.routers.visualizer.tls.certresolver=myresolver"
        - "traefik.http.services.visualizer.loadbalancer.server.port=8080"
    ports:
      - "8080:8080"

networks:
  backend_network:
    driver: overlay
  frontend_network:
    driver: overlay
  traefik_network:
    driver: overlay

volumes:
  primary_data:
    driver: local
  replica_data:
    driver: local
  pgadmin_data:
    driver: local
  traefik_data:
    driver: local