FROM edoburu/pgbouncer:latest

COPY pgbouncer/pgbouncer.ini /etc/pgbouncer/pgbouncer.ini
COPY pgbouncer/userlist.txt /etc/pgbouncer/userlist.txt
COPY ./dns_wait.sh /usr/local/bin/dns_wait.sh


EXPOSE 6432